{{- if (include "spring.redis.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-spring-redis" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "spring.redis.secretPasswordKey" . }}: {{ .Values.spring.redis.password | b64enc | quote }}
{{- end }}
