annotations:
  category: Application
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.x.x
dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Spring Boot is an open source Java-based framework used to create a micro Service.
home: https://spring.io/projects/spring-boot
icon: https://spring.io/img/logos/spring-initializr.svg
keywords:
  - spring
  - java
  - cloud
  - boot
  - microservices
  - web applications
  - serverless
  - batch
  - event driven
  - reactive
maintainers:
  - name: nentangso
    url: https://github.com/nentangso
name: spring-boot-app
sources:
  - https://github.com/spring-projects/spring-boot
version: 0.1.5
