annotations:
  category: Application
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.x.x
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Deploy simple webapp, ex reactjs
home: https://github.com/nentangso/charts/tree/main/nentangso/webapp
icon: https://cdn.cdnlogo.com/logos/r/63/react.svg
keywords:
  - web applications
  - webapp
  - sinple page app (SPA)
maintainers:
  - name: nentangso
    url: https://github.com/nentangso
name: webapp
sources:
  - https://github.com/nentangso/charts/tree/main/nentangso/webapp
version: 0.1.9